//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_clientes", Namespace="http://schemas.datacontract.org/2004/07/Datos.Modelo")]
    [System.SerializableAttribute()]
    public partial class vw_clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_identificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                if ((this.id_clienteField.Equals(value) != true)) {
                    this.id_clienteField = value;
                    this.RaisePropertyChanged("id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_direccion {
            get {
                return this.id_direccionField;
            }
            set {
                if ((this.id_direccionField.Equals(value) != true)) {
                    this.id_direccionField = value;
                    this.RaisePropertyChanged("id_direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.identificacionField, value) != true)) {
                    this.identificacionField = value;
                    this.RaisePropertyChanged("identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apellidoField, value) != true)) {
                    this.primer_apellidoField = value;
                    this.RaisePropertyChanged("primer_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_nombre {
            get {
                return this.primer_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_nombreField, value) != true)) {
                    this.primer_nombreField = value;
                    this.RaisePropertyChanged("primer_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apellidoField, value) != true)) {
                    this.segundo_apellidoField = value;
                    this.RaisePropertyChanged("segundo_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_identificacion {
            get {
                return this.tipo_identificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_identificacionField, value) != true)) {
                    this.tipo_identificacionField = value;
                    this.RaisePropertyChanged("tipo_identificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_direccion", Namespace="http://schemas.datacontract.org/2004/07/Datos.Modelo")]
    [System.SerializableAttribute()]
    public partial class vw_direccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICliente")]
    public interface ICliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/Alta", ReplyAction="http://tempuri.org/ICliente/AltaResponse")]
        void Alta(string n_identificacion, string tipo_identificacion, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, int id_direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/Alta", ReplyAction="http://tempuri.org/ICliente/AltaResponse")]
        System.Threading.Tasks.Task AltaAsync(string n_identificacion, string tipo_identificacion, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, int id_direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/Modificar", ReplyAction="http://tempuri.org/ICliente/ModificarResponse")]
        void Modificar(int id, string n_identificacion, string tipo_identificacion, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, int id_direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/Modificar", ReplyAction="http://tempuri.org/ICliente/ModificarResponse")]
        System.Threading.Tasks.Task ModificarAsync(int id, string n_identificacion, string tipo_identificacion, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, int id_direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/Baja", ReplyAction="http://tempuri.org/ICliente/BajaResponse")]
        void Baja(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/Baja", ReplyAction="http://tempuri.org/ICliente/BajaResponse")]
        System.Threading.Tasks.Task BajaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/ObtenerClientes", ReplyAction="http://tempuri.org/ICliente/ObtenerClientesResponse")]
        TestApp.ServiceReference1.vw_clientes[] ObtenerClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/ObtenerClientes", ReplyAction="http://tempuri.org/ICliente/ObtenerClientesResponse")]
        System.Threading.Tasks.Task<TestApp.ServiceReference1.vw_clientes[]> ObtenerClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/ObtenerDireccion", ReplyAction="http://tempuri.org/ICliente/ObtenerDireccionResponse")]
        TestApp.ServiceReference1.vw_direccion[] ObtenerDireccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/ObtenerDireccion", ReplyAction="http://tempuri.org/ICliente/ObtenerDireccionResponse")]
        System.Threading.Tasks.Task<TestApp.ServiceReference1.vw_direccion[]> ObtenerDireccionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteChannel : TestApp.ServiceReference1.ICliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteClient : System.ServiceModel.ClientBase<TestApp.ServiceReference1.ICliente>, TestApp.ServiceReference1.ICliente {
        
        public ClienteClient() {
        }
        
        public ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Alta(string n_identificacion, string tipo_identificacion, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, int id_direccion) {
            base.Channel.Alta(n_identificacion, tipo_identificacion, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, id_direccion);
        }
        
        public System.Threading.Tasks.Task AltaAsync(string n_identificacion, string tipo_identificacion, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, int id_direccion) {
            return base.Channel.AltaAsync(n_identificacion, tipo_identificacion, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, id_direccion);
        }
        
        public void Modificar(int id, string n_identificacion, string tipo_identificacion, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, int id_direccion) {
            base.Channel.Modificar(id, n_identificacion, tipo_identificacion, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, id_direccion);
        }
        
        public System.Threading.Tasks.Task ModificarAsync(int id, string n_identificacion, string tipo_identificacion, string primer_nombre, string segundo_nombre, string primer_apellido, string segundo_apellido, int id_direccion) {
            return base.Channel.ModificarAsync(id, n_identificacion, tipo_identificacion, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, id_direccion);
        }
        
        public void Baja(int id) {
            base.Channel.Baja(id);
        }
        
        public System.Threading.Tasks.Task BajaAsync(int id) {
            return base.Channel.BajaAsync(id);
        }
        
        public TestApp.ServiceReference1.vw_clientes[] ObtenerClientes() {
            return base.Channel.ObtenerClientes();
        }
        
        public System.Threading.Tasks.Task<TestApp.ServiceReference1.vw_clientes[]> ObtenerClientesAsync() {
            return base.Channel.ObtenerClientesAsync();
        }
        
        public TestApp.ServiceReference1.vw_direccion[] ObtenerDireccion() {
            return base.Channel.ObtenerDireccion();
        }
        
        public System.Threading.Tasks.Task<TestApp.ServiceReference1.vw_direccion[]> ObtenerDireccionAsync() {
            return base.Channel.ObtenerDireccionAsync();
        }
    }
}
